# GRPO configuration for DeepSeek-OCR on document understanding tasks.
data:
  train_files: lmms-lab/DocVQA@train
  val_files: lmms-lab/DocVQA@validation
  prompt_key: question
  answer_key: answer
  image_key: image
  image_dir: null
  max_prompt_length: 2048
  max_response_length: 512
  rollout_batch_size: 256
  mini_rollout_batch_size: 64
  val_batch_size: 128
  format_prompt: ./examples/format_prompt/ocr.jinja
  override_chat_template: null
  shuffle: true
  seed: 2
  min_pixels: 262144
  max_pixels: 4194304
  filter_overlong_prompts: true

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 5.0e-3
  online_filtering: false
  filter_key: overall
  filter_low: 0.05
  filter_high: 0.95

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 2
    max_grad_norm: 1.0
    padding_free: true
    dynamic_batching: true
    ulysses_size: 1
    model:
      model_path: deepseek-ai/deepseek-ocr
      enable_gradient_checkpointing: true
      trust_remote_code: true
      freeze_vision_tower: false
      processor:
        image_grid_pin_memory: true
        use_cached_image_grid: true
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw
      lr_warmup_ratio: 0.01
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 4
    temperature: 0.8
    top_p: 0.9
    limit_images: 0
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: true
    tensor_parallel_size: 2
    disable_tqdm: false
    val_override_config:
      temperature: 0.2
      top_p: 0.8
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/ocr.py:compute_score

trainer:
  total_epochs: 3
  max_steps: null
  project_name: easy_r1
  experiment_name: deepseek_ocr_docvqa_grpo
  logger: ["file"]
  nnodes: 1
  n_gpus_per_node: 8
  max_try_make_batch: 20
  val_freq: 1
  val_before_train: true
  val_only: false
  val_generations_to_log: 3
  save_freq: 1
  save_limit: 2
  save_model_only: false
  save_checkpoint_path: null
  load_checkpoint_path: null
  find_last_checkpoint: true
